import localFont from "next/font/local";
import "./globals.scss";

const myFont = localFont({
  src: "./fonts/SFProDisplay-Regular.woff2",
  display: "swap",
  variable: "--my-font",
});

export const metadata = {
  title: "Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className={myFont.className} lang="en">
      <body>{children}</body>
    </html>
  );
}
